server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heimacloud_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1q2w3e
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 微服务名称
  application:
    name: orderServer
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: xiaobai # 集群名称
        namespace: 37e985ed-3703-45bb-9252-8e01e1b5f852 # 名称空间的id
        ephemeral: false # 是否是临时实例 
mybatis:
  type-aliases-package: com.xiaobai.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# eureka地址信息
eureka:
  client:
    server-url: http://localhost:8761/eureka

# 自定义负载均衡
userServer:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

# 饥饿加载
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients: # 执行饥饿加载的服务名称，是一个集合，项目启动时直接去拉取userServer的集群
#      - userServer